---

- hosts: all
  become: true
  tasks:

  - name: update repos install apache2 & php package
    apt:
      name:
      - apache2
      - libapache2-mod-php
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'