[proxmox]
pve01 ansible_host=192.168.1.10

[docker_vms]
docker ansible_host=192.168.1.75

[ubuntu_vms]
pihole ansible_host=192.168.1.6
ansible ansible_host=192.168.1.5
tandoor ansible_host=tandoor.home.lan
homer ansible_host=homer.home.lan


[proxmox:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa

[pihole_vms:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_rsa

[docker_vms:vars]
ansible_user=colin
ansible_ssh_private_key_file=~/.ssh/id_rsa

