---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 & php package
    apt:
      update_cache: yes
      pkg:
      - apache2
      - libapache2-mod-php
      state: absent
    when: ansible_distribution == 'Ubuntu'
