---

- hosts: all
  become: true
  tasks:

  - name: install updates Ubuntu
    apt:
      update_cache: yes
      upgrade: dist
    when : ansible_facts["distribution"] == 'Ubuntu'
  
  - name: install updates Debian
    apt:
      update_cache: yes
      upgrade: dist
    when : ansible_facts["distribution"] == 'Debian'

- hosts: all
  become: true
  tasks:

    - name: create serveradmin users
      user:
        name: serveradmin
        group: users
  
- hosts: web_server
  become: true
  tasks:

  - name: install apache & php
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest

  - name: copy default html file
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb
    apt:
      name:
      - mariadb-server
      state: latest

- hosts: file_server
  become: true
  tasks:
  
  - name: install samba
    apt:
      name:
      - samba
      state: latest


 